/**
 * Фабрики мок-данных для E2E тестов
 */

export const mockUsers = {
  renter: {
    _id: 'user-renter-1',
    name: 'Иван Арендатор',
    email: 'renter@test.com',
    phone: '+79001234567',
    role: 'renter' as const,
    rating: 4.5,
    reviewCount: 3,
    trustScore: 75,
    isVerified: false,
    is_verified: false,
    createdAt: '2025-01-01T00:00:00Z',
    defaultApprovalMode: 'auto_approve' as const,
    approvalRatingThreshold: 4.0,
  },
  owner: {
    _id: 'user-owner-1',
    name: 'Мария Владелец',
    email: 'owner@test.com',
    phone: '+79009876543',
    role: 'owner' as const,
    rating: 4.8,
    reviewCount: 10,
    trustScore: 90,
    isVerified: true,
    is_verified: true,
    verification_status: 'verified' as const,
    createdAt: '2024-06-15T00:00:00Z',
    defaultApprovalMode: 'manual' as const,
    approvalRatingThreshold: 4.0,
  },
  admin: {
    _id: 'user-admin-1',
    name: 'Админ Платформы',
    email: 'admin@test.com',
    phone: '+79005555555',
    role: 'admin' as const,
    rating: 5.0,
    reviewCount: 0,
    trustScore: 100,
    isVerified: true,
    is_verified: true,
    createdAt: '2024-01-01T00:00:00Z',
    defaultApprovalMode: 'auto_approve' as const,
    approvalRatingThreshold: 4.0,
  },
};

export const mockItems = [
  {
    _id: 'item-1',
    title: 'Камера Sony A7III',
    description: 'Профессиональная камера для фото и видео. Полный комплект с объективом 28-70.',
    category: 'Электроника',
    pricePerDay: 3000,
    pricePerMonth: 50000,
    deposit: 15000,
    photos: ['/uploads/camera.jpg'],
    status: 'approved',
    ownerId: mockUsers.owner._id,
    owner: mockUsers.owner,
    rating: 4.7,
    reviewCount: 5,
    location: { lat: 55.7558, lng: 37.6173, address: 'Москва, Тверская ул., 1' },
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    _id: 'item-2',
    title: 'Велосипед Trek Marlin 7',
    description: 'Горный велосипед для активного отдыха. Размер рамы M.',
    category: 'Спорт',
    pricePerDay: 1500,
    pricePerMonth: 25000,
    deposit: 10000,
    photos: ['/uploads/bike.jpg'],
    status: 'approved',
    ownerId: mockUsers.owner._id,
    owner: mockUsers.owner,
    rating: 4.2,
    reviewCount: 3,
    location: { lat: 55.76, lng: 37.62, address: 'Москва, Пушкинская пл.' },
    createdAt: '2025-02-15T00:00:00Z',
  },
  {
    _id: 'item-3',
    title: 'Дрель Bosch Professional',
    description: 'Аккумуляторная дрель-шуруповёрт. 2 аккумулятора, зарядное, кейс.',
    category: 'Инструменты',
    pricePerDay: 500,
    pricePerMonth: 8000,
    deposit: 3000,
    photos: ['/uploads/drill.jpg'],
    status: 'approved',
    ownerId: mockUsers.owner._id,
    owner: mockUsers.owner,
    rating: 4.9,
    reviewCount: 8,
    location: { lat: 55.75, lng: 37.61, address: 'Москва, Арбат' },
    createdAt: '2025-01-20T00:00:00Z',
  },
];

export const mockBookings = [
  {
    _id: 'booking-1',
    itemId: 'item-1',
    item: mockItems[0],
    renterId: mockUsers.renter._id,
    renter: mockUsers.renter,
    ownerId: mockUsers.owner._id,
    owner: mockUsers.owner,
    startDate: '2026-02-10T00:00:00Z',
    endDate: '2026-02-15T00:00:00Z',
    status: 'pending_approval',
    totalPrice: 15000,
    deposit: 15000,
    insurance: false,
    createdAt: '2026-02-06T10:00:00Z',
    reviews: [],
  },
  {
    _id: 'booking-2',
    itemId: 'item-2',
    item: mockItems[1],
    renterId: mockUsers.renter._id,
    renter: mockUsers.renter,
    ownerId: mockUsers.owner._id,
    owner: mockUsers.owner,
    startDate: '2026-01-01T00:00:00Z',
    endDate: '2026-01-10T00:00:00Z',
    status: 'completed',
    totalPrice: 13500,
    deposit: 10000,
    insurance: true,
    createdAt: '2025-12-25T10:00:00Z',
    reviews: [],
  },
];

export const mockConversations = [
  {
    bookingId: 'booking-1',
    itemTitle: 'Камера Sony A7III',
    itemPhoto: '/uploads/camera.jpg',
    otherUser: { _id: mockUsers.owner._id, name: mockUsers.owner.name },
    lastMessage: { text: 'Здравствуйте! Камера доступна в эти даты.', createdAt: '2026-02-06T11:00:00Z' },
    unreadCount: 1,
  },
];

export const mockMessages = [
  {
    _id: 'msg-1',
    bookingId: 'booking-1',
    senderId: mockUsers.renter._id,
    text: 'Здравствуйте! Хотел бы арендовать камеру.',
    createdAt: '2026-02-06T10:30:00Z',
    isRead: true,
  },
  {
    _id: 'msg-2',
    bookingId: 'booking-1',
    senderId: mockUsers.owner._id,
    text: 'Здравствуйте! Камера доступна в эти даты.',
    createdAt: '2026-02-06T11:00:00Z',
    isRead: false,
  },
];

export const mockReviews = [
  {
    _id: 'review-1',
    bookingId: 'booking-2',
    userId: mockUsers.renter._id,
    user: mockUsers.renter,
    rating: 5,
    text: 'Отличный велосипед! Всё в идеальном состоянии, рекомендую.',
    photos: [],
    type: 'renter_review',
    createdAt: '2026-01-12T10:00:00Z',
  },
];

export const mockNotificationSettings = {
  emailNotifications: true,
  pushNotifications: false,
  telegramLinked: false,
  telegramChatId: null,
  vkLinked: false,
  vkUserId: null,
  notifyBookingRequests: true,
  notifyMessages: true,
  notifyReviews: true,
  notifyStatusChanges: true,
};
